<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.17"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.17" PrivateAssets="all"/>
        <PackageReference Include="Append.Blazor.Clipboard" Version="1.0.0" />
        <PackageReference Include="Radzen.Blazor" Version="7.1.4" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
        <PackageReference Include="PdfPig" Version="0.1.10" />
        <PackageReference Include="Tewr.Blazor.FileReader" Version="3.4.0.24340" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Data\Transactions\Transaction.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MoneyManagement_Data\MoneyManagement_Data.csproj" />
    </ItemGroup>

</Project>
